### ISSUE TITLE
create_pcdb error

### ISSUE THREAD

**Issue by krystineg** [HeldLab/ProteoClade#1]
when running the create_pcdb step, using a mouse and human fasta file, I am getting the below error and it seems to be skipping over the mouse fasta file but running through the human one. Should I be feeding it the merged fasta file instead? I did not see any notes for what the fasta should be, except whatever is in the "fastas" directory.
`Reading from file uniprot-mouse_downloaded_20170329_TXID10090.fasta`
`Process Process-8:`
`Traceback (most recent call last):`
`File "packages/python/3.6.0/lib/python3.6/multiprocessing/process.py", line249, in _bootstrap self.run()`
`File "packages/python/3.6.0/lib/python3.6/multiprocessing/process.py", line93, in run self._target(*self._args, **self._kwargs)`
`File"/scratch/kgarcia/ProteoClade_test/ProteocClade/proteoclade/pcdb.py", line 310, in _writer c.execute("Begin EXCLUSIVE TRANSACTION")`
`sqlite3.OperationalError: cannot start a transaction within a transaction`
`Reading from file uniprot-human_downloaded_20170329_TXID9606.fasta`

Thank you.

**Comment by admooradian** [comment]
Thanks to @krystineg for identifying and helping us troubleshoot this issue. The exclusive transaction line caused an SQL error on specific platforms. The offending line was removed with minimal performance impact and has resolved the error
